USE Master
GO
IF EXISTS (SELECT * FROM sys.databases WHERE Name='SchoolFPT')
DROP DATABASE SchoolFPT
GO
CREATE DATABASE SchoolFPT
GO
USE SchoolFPT
GO
CREATE TABLE Student(
	SID INT IDENTITY (1, 1) PRIMARY KEY,
	S_FNAME VARCHAR(50) NOT NULL,
	S_LNAME VARCHAR(50) NOT NULL
	)
CREATE TABLE Course(
	CID INT IDENTITY(1,1) PRIMARY KEY,
	C_NAME VARCHAR(50) NOT NULL
	)
CREATE TABLE Course_Grades (
	CGID INT IDENTITY (1,1) PRIMARY KEY,
	Semester CHAR(4) NOT NULL,
	CID INT NOT NULL,
	SID INT NOT NULL,
	Grade CHAR(2) NOT NULL,
	CONSTRAINT FK_SID FOREIGN KEY (SID) REFERENCES Student(SID),
	CONSTRAINT FK_CID FOREIGN KEY (CID) REFERENCES Course(CID),
	)
--3
ALTER TABLE Student ALTER COLUMN s_FNAME VARCHAR(30)	

--4
ALTER TABLE Course_Grades
ADD Faculty_LName VARCHAR(30)


--5
UPDATE Course
SET C_NAME='Intro to Wizardry'
WHERE CID=101001


--6
ALTER TABLE Course
RENAME COLUMN C_NAME to Course_Name

DELETE FROM Course
WHERE CID=101004

--8
DROP TABLE Student

--9
TRUNCATE TABLE Course

--10
ALTER TABLE Course_Grades
DROP CONSTRAINT CID,SID
